<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>dynamics-crm-lab</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DynamicsCrmLab.Api.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DynamicsCrmLab.Infrastructure\DynamicsCrmLab.Infrastructure.csproj" />
  </ItemGroup>

</Project>
